-- USER SQL
ALTER USER "HR" IDENTIFIED BY "hi123456" 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "HR" QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER "HR" DEFAULT ROLE "CONNECT","RESOURCE";

-- ----------------------------------------------
-- USER SQL
CREATE USER "TEST" IDENTIFIED BY "hi123456"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "TEST" ;
GRANT "RESOURCE" TO "TEST" ;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "TEST" ;



-- java계정 생성,권한3종부여, 접속
-- USER SQL
CREATE USER "JAVA" IDENTIFIED BY "hi123456"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "JAVA" ;
GRANT "RESOURCE" TO "JAVA" ;

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "JAVA" ;